---
# Default variables for roles/traefik

# Subdomains & Authentication defaults
traefik_dashboard_subdomain: "traefik"
traefik_dashboard_user: "admin"

# Infrastructure & Directories
traefik_install_dir: "/opt/traefik"
traefik_network_name: "traefik-public"
traefik_image_tag: "v3"
traefik_log_level: "INFO"

# Built-in Verification Service
traefik_deploy_whoami: true
traefik_whoami_subdomain: "whoami"
