services:
  hello:
    image: traefik/whoami:latest
    container_name: lab-hello-service
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.rule=Host(`hello.example.com`)"
      - "traefik.http.services.hello.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
