---
# Base Domain & ACME settings
traefik_base_domain: "example.com"
traefik_acme_email: "admin@example.com"

# Traefik Dashboard Credentials
traefik_dashboard_subdomain: "traefik"
traefik_dashboard_user: "admin"
traefik_dashboard_password: "ChangeMeInVault!"

# Infrastructure & Directories
traefik_install_dir: "/opt/traefik"
traefik_network_name: "traefik-public"
traefik_image_tag: "v3.1"
traefik_log_level: "INFO"

# Built-in Verification Service
traefik_deploy_whoami: true
traefik_whoami_subdomain: "whoami"
